# Generated by Django 3.2.18 on 2023-05-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='position',
            field=models.CharField(blank=True, choices=[('Visiting Professor', 'Visiting Professor'), ('Lecturer on Law', 'Lecturer on Law')], default='Lecturer on Law', max_length=64),
        ),
    ]
