# Generated by Django 3.2.18 on 2023-05-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_professor_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.AddField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='coarseload', to='allocation.Course'),
        ),
    ]
